simple_proto: fix printing of protocol name if BUGON is #defined
If BUGON is defined, then a compilation error occurs because the
dumping of the shared descriptor contains a leftover variable
(pre-refactoring). This patch fixes this issue by referencing
the proper member of the protocol structure.

Change-Id: Ia8398bd17e58123ac0d17dd8289ecd82ba7cce11
Signed-off-by: Alex Porosanu <alexandru.porosanu@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/6277
Reviewed-by: Cristian Stoica <cristian.stoica@freescale.com>
Reviewed-by: Vakul Garg <vakul@freescale.com>
Tested-by: Vakul Garg <vakul@freescale.com>