poc: Fix a build issue when POC_TRACE is defined
apps/poc.c: In function 'cb_dqrr_2fwd':
apps/poc.c:367:34: error: 'struct poc_fq_2fwd' has no member named 'tx'

Signed-off-by: Emil Medve <Emilian.Medve@Freescale.com>