fra: Remove the duplicate address member
Original structure rman_outb_md contains the two address members,
it will result in a compilation error with gcc 4.6:

apps/fra/include/rman_interface.h:96:11: error: duplicate member 'address'

According to the DPAARM Rev.2, word0 of the RMan outbound descriptor
does not contain the address field, so just remove the duplicate
and unused address member from word0

Signed-off-by: Minghuan Lian <Minghuan.Lian@freescale.com>