Revert "ppac: allow PPAMs to register and seed datapath pools"
This reverts commit 95abec6ec85d390b27a978aaf6d2422f59658a72

This patch breaks usdpaa compilation with error:

apps/ppac/main.c: In function 'do_global_init':
apps/ppac/main.c:658:8: error: 'bp_depletion' undeclared (first use in this function)

Change-Id: I8a5a4858386ee9cc727be0764b27b2977a154a7d
Reviewed-on: http://git.am.freescale.net:8181/518
Reviewed-by: Garg Vakul-B16394 <vakul@freescale.com>
Tested-by: Garg Vakul-B16394 <vakul@freescale.com>